name: falldetectionapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  firebase_core: ^2.22.0
  firebase_database: ^10.3.4
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  location: ^5.0.3
  mailer: ^6.0.1
  permission_handler: ^11.0.1
  sensors: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
